version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: x64
build:
  project: waifu2x_ncnn_vulkan_gui.sln
  verbosity: normal
artifacts:
- path: waifu2x_i18n_gui\bin\x64\Release\waifu2x_ncnn_vulkan_gui.exe
- path: waifu2x_i18n_gui\ja-JP\UIlang.ja-JP.xaml
- path: waifu2x_i18n_gui\en-US\UILang.en-US.xaml
